extends: [".spectral.yaml"]
rules:
  array-properties-must-have-items-with-type: off
  array-parameters-must-have-items-with-type: off
  array-parameters-must-have-serialisation-info: off
  element-must-have-description: off
  schema-must-be-valid: off
  use-valid-media-type: off
  reuse-schemas-in-media-types: off
