---
title: Product Price Point Currency Price
type: object
properties:
  id:
    type: integer
  currency:
    type: string
  price:
    type: integer
  formatted_price:
    type: string
  product_price_point_id:
    type: integer
  role:
    type: string
    enum:
    - baseline
    - trial
    - initial
examples:
- id: 0
  currency: string
  price: 0
  formatted_price: string
  product_price_point_id: 0
  role: baseline
- id: 0
  currency: string
  price: 0
  formatted_price: string
  product_price_point_id: 0
  role: baseline
description: 'object Product Price Point Currency Price:

  '
