openapi: 3.0.0
info:
  title: Chargify
  version: '1.0'
  contact:
    email: support@chargify.com
  description: Manage your company's subscriptions through the Chargify API.
tags:
  - name: Webhooks
paths:
  /webhooks.json:
    get:
      summary: List Webhooks
      tags:
        - Webhooks
      responses: {}
      operationId: get-webhooks.json
components:
  schemas: {}
servers:
  - url: 'https://subdomain.chargify.com'
    description: ''
