openapi: 3.0.0
info:
  title: Chargify
  version: '1.0'
  contact:
    email: support@chargify.com
  description: Manage your company's subscriptions through the Chargify API.
tags:
  - name: Legacy Subscription Balance
paths:
  '/subscriptions/{subscription_id}/adjustments.json':
    parameters:
      - schema:
          type: string
        name: subscription_id
        in: path
        required: true
        description: The Chargify id of the subscription to which the adjustment applies
    post:
      summary: Create Adjustment
      tags:
        - Legacy Subscription Balance
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  adjustment:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: The Chargify id of the adjustment
                      success:
                        type: boolean
                        description: Boolean indicating if the adjustment was successfully applied to the subscription balance
                      memo:
                        type: string
                        description: The supplied description of the adjustment
                        maxLength: 255
                      amount_in_cents:
                        type: integer
                        description: The amount of the adjustment represented in cents
                      ending_balance_in_cents:
                        type: integer
                        description: The subscription balance after the adjustment was applied
                      type:
                        type: string
                      transaction_type:
                        type: string
                      subscription_id:
                        type: integer
                        description: The Chargify id of the subscription associated with this adjustment
                      product_id:
                        type: integer
                        description: The Chargify id of the product associated with the subscription's at the time of the adjustment
                      created_at:
                        type: string
                        description: The time that the adjustment was created
                      updated_at:
                        type: string
                        description: The time at which the adjustment was last updated
                      payment_id:
                        type: integer
                        nullable: true
                      period_range_start:
                        type: string
                        nullable: true
                        format: date
                        description: The start of the billing period for which the adjustment applies
                      period_range_end:
                        type: string
                        nullable: true
                        format: date
                        description: The end of the billing period period for which the adjustment applies
      operationId: post-subscriptions-subscriptionId-adjustments.json
      description: |-
        ## Adjustments Documentation 

        Full documentation on how to record Adjustments in the Chargify UI can be located [here](http://help.chargify.com/subscriptions/adjustments.html). It goes into greater detail on how the user interface will react when applying adjustments.


        ## Scenarios for adjustments

        | Scenario 1 | To create an Adjustment on a Subscription to increase the balance by a certain dollar amount, include the following to your request: | `"amount":"4.00"`                                            |
        |------------|--------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------|
        | Scenario 2 | To increase the Subscription balance by a certain amount of cents, use the following attribute in your request:                      | `"amount_in_cents":100`                                      |
        | Scenario 3 | To decrease the Subscription balance by a certain dollar amount, the request must contain:                                           | `"amount":"-4.00"`                                           |
        | Scenario 4 | To decrease the Subscription balance by a certain amount of cents, use:                                                              | `"amount_in_cents":"-400"`                                   |
        | Scenario 5 | To set the Subscription balance to an exact dollar amount, include the following attributes to the request:                          | `"adjustment_method":"target", "amount":"100.00"`            |
        | Scenario 6 | To set the Subscription balance to an exact positive amount of cents, the request must contain the following attributes:             | `"adjustment_method":"target",` `"amount_in_cents":"10000"`  |
        | Scenario 7 | To set the Subscription balance to an exact negative amount of cents, use the following attributes in the request:                   | `"adjustment_method":"target",` `"amount_in_cents":"-10000"` |
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                adjustment:
                  type: object
                  properties:
                    amount:
                      oneOf:
                        - type: string
                        - type: number
                      description: '(either amount or amount_in_cents is required) If you use this parameter, you should pass a dollar amount represented as a string. For example, $10.00 would be represented as 10.00 and -$10.00 would be represented as -10.00.'
                    memo:
                      type: string
                      description: A helpful explanation for the adjustment. This amount will remind you and your customer for the reason for the assessment of the adjustment.
                      maxLength: 255
                    amount_in_cents:
                      oneOf:
                        - type: string
                        - type: number
                    period_range_start:
                      type: string
                      description: 'A date range represents a service period. If a start is provided, an end must be supplied as well. These dates are optional and do not impact the billing of the charge. If provided, the date range will be used for revenue placement on the Finance Report and Revenue Recognition report.'
                      format: date
                    period_range_end:
                      type: string
                      description: 'A date range represents a service period. If an end is provided, a start must be supplied as well. These dates are optional and do not impact the billing of the charge. If provided, the date range will be used for revenue placement on the Finance Report and Revenue Recognition report.'
                      format: date
                    adjustment_method:
                      type: string
                      enum:
                        - target
                      description: 'A string that toggles how the adjustment should be applied. If target is passed for this param, the adjustment will automatically set the subscription’s balance to the amount. If left blank, the amount will be added to the current balance.'
                  required:
                    - amount
                    - memo
components:
  schemas: {}
servers:
  - url: 'https://subdomain.chargify.com'
    description: ''
