title: Upsert Prepaid Configuration
type: object
properties:
  initial_funding_amount_in_cents:
    type: integer
    format: int64
  replenish_to_amount_in_cents:
    type: integer
    format: int64
  auto_replenish:
    type: boolean
  replenish_threshold_amount_in_cents:
    type: integer
    format: int64
