---
"/product_families.json":
  post:
    summary: Create Product Family
    tags:
    - Product Families
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              type: object
              properties:
                product_family:
                  "$ref": "../models/Product-Family.yaml"
            examples:
              Example:
                value:
                  product_family:
                    id: 933860
                    name: Acme Projects
                    description: Amazing project management tool
                    handle: acme-projects
                    accounting_code:
    operationId: createProductFamily
    description: |-
      This method will create a Product Family within your Chargify site. Create a Product Family to act as a container for your products, components and coupons.

      Full documentation on how Product Families operate within the Chargify UI can be located [here](https://maxio-chargify.zendesk.com/hc/en-us/articles/5405369633421).
    requestBody:
      content:
        application/json:
          schema:
            type: object
            properties:
              product_family:
                type: object
                properties:
                  name:
                    type: string
                  description:
                    type: string
          examples:
            Example:
              value:
                product_family:
                  name: Acme Projects
                  description: Amazing project management tool
  get:
    summary: List Product Families
    tags:
    - Product Families
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  product_family:
                    "$ref": "../models/Product-Family.yaml"
            examples:
              Example:
                value:
                - product_family:
                    id: 37
                    name: Acme Projects
                    description:
                    handle: acme-projects
                    accounting_code:
                    created_at: '2013-02-20T15:05:51-07:00'
                    updated_at: '2013-02-20T15:05:51-07:00'
                - product_family:
                    id: 155
                    name: Bat Family
                    description: Another family.
                    handle: bat-family
                    accounting_code:
                    created_at: '2014-04-16T12:41:13-06:00'
                    updated_at: '2014-04-16T12:41:13-06:00'
    operationId: listProductFamilies
    description: This method allows to retrieve a list of Product Families for a site.
    parameters:
    - schema:
        type: string
        enum:
        - created_at
        - updated_at
      in: query
      name: date_field
      description: The type of filter you would like to apply to your search.
    - schema:
        type: string
      in: query
      name: start_date
      description: " The start date (format YYYY-MM-DD) with which to filter the date_field.
        Returns products with a timestamp at or after midnight (12:00:00 AM) in your
        site’s time zone on the date specified."
    - schema:
        type: string
      in: query
      name: end_date
      description: The end date (format YYYY-MM-DD) with which to filter the date_field.
        Returns products with a timestamp up to and including 11:59:59PM in your site’s
        time zone on the date specified.
    - schema:
        type: string
      in: query
      name: start_datetime
      description: The start date and time (format YYYY-MM-DD HH:MM:SS) with which
        to filter the date_field. Returns products with a timestamp at or after exact
        time provided in query. You can specify timezone in query - otherwise your
        site's time zone will be used. If provided, this parameter will be used instead
        of start_date.
    - schema:
        type: string
      in: query
      name: end_datetime
      description: The end date and time (format YYYY-MM-DD HH:MM:SS) with which to
        filter the date_field. Returns products with a timestamp at or before exact
        time provided in query. You can specify timezone in query - otherwise your
        site's time zone will be used. If provided, this parameter will be used instead
        of end_date.
