title: Invoice Payment Application
type: object
properties:
  invoice_uid:
    type: string
    description: |
      Unique identifier for the paid invoice. It has the prefix "inv_" followed by alphanumeric characters.
  application_uid:
    type: string
    description: |
      Unique identifier for the payment. It has the prefix "pmt_" followed by alphanumeric characters.
  applied_amount:
    type: string
    description: Dollar amount of the paid invoice.
