title: Prepaid Configuration
type: object
properties:
  id:
    type: integer
  initial_funding_amount_in_cents:
    type: integer
  replenish_to_amount_in_cents:
    type: integer
  auto_replenish:
    type: boolean
  replenish_threshold_amount_in_cents:
    type: integer
