title: Product Family
type: object
properties:
  id:
    type: integer
  name:
    type: string
  handle:
    type: string
  accounting_code:
    type:
      - "null"
      - string
  description:
    type:
      - string
      - "null"
  created_at:
    type: string
  updated_at:
    type: string
