title: Site
type: object
properties:
  id:
    type: integer
  name:
    type: string
  subdomain:
    type: string
  currency:
    type: string
  seller_id:
    type: integer
  non_primary_currencies:
    type: array
    items:
      type: string
  relationship_invoicing_enabled:
    type: boolean
  customer_hierarchy_enabled:
    type: boolean
  whopays_enabled:
    type: boolean
  whopays_default_payer:
    type: string
  allocation_settings:
    $ref: "./Allocation-Settings.yaml"
  default_payment_collection_method:
    type: string
  organization_address:
    $ref: "./Organization-Address.yaml"
  tax_configuration:
    $ref: "./Tax-Configuration.yaml"
  net_terms:
    $ref: "./Net-Terms.yaml"
  test:
    type: boolean
