title: Tax Configuration
type: object
properties:
  kind:
    $ref: "./Tax-Configuration-Kind.yaml"
  destination_address:
    $ref: "./Tax-Destination-Address.yaml"
  fully_configured:
    type: boolean
    default: false
    description: "Returns `true` when Chargify has been properly configured to charge tax using the specified tax system. More details about taxes: https://maxio-chargify.zendesk.com/hc/en-us/articles/5405488905869-Taxes-Introduction"
