name: Publish SDKs to their Git repositories
on:
  workflow_dispatch:
    inputs:
      sdkType:
        description: 'SDK type'
        required: true
        default: 'All'
        type: choice
        options:
          - All
          - Java
          - Python
          - Ruby
          - Js
      prTitle:
        description: 'PR summary'
        required: true
        type: string
      prDescription:
        description: 'PR description'
        type: string
        required: true
jobs:
  run-generator:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sdk-generator
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3
      - name: Checkout sdk-generator
        uses: actions/checkout@v3
        with:
          repository: maxio-com/sdk-generator
          ref: refs/tags/v1.0.2
          path: sdk-generator
          token: ${{ secrets.SDK_GENERATOR_TOKEN }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Publish SDKs
        shell: bash
        run: ./gradlew clean publish${{ inputs.sdkType }}Sdk -PoverrideApiDocsRelativePath=.. -PreleaseTitle=${{ inputs.prTitle }} >
          -PreleaseMessage=${{ inputs.prDescription }} -PreleaseBranch=release-${{ github.sha }}-${{ github.run_id }}-${{ github.run_attempt }}

