name: Push changes to APIMatic
on: workflow_dispatch
jobs:
  apimatic-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repository
        uses: actions/checkout@v3
        with:
          ref: v2
      - name: Zip files
        run: zip -r maxio-api.zip ./portal/spec
      - name: Import to APIMatic
        run: |
          curl -X PUT -sS --url 'https://api.apimatic.io/api-entities/${{ secrets.API_ENTITY_ID }}/import-via-file' \
            -H 'Content-Type:multipart/form-data' \
            -H 'Accept: application/vnd.apimatic.apiEntity.full.v1+json' \
            -H 'Authorization:X-Auth-Key ${{ secrets.APIMATIC_API_KEY }}' \
            -F 'file=@maxio-api.zip'
