title: Create or Update Prepaid Configuration
type: object
x-tags:
  - Subscriptions
properties:
  initial_funding_amount_in_cents:
    type: integer
  replenish_to_amount_in_cents:
    type: integer
  auto_replenish:
    type: boolean
  replenish_threshold_amount_in_cents:
    type: integer