title: Product Price Point Currency Price
type: object
x-tags:
  - Product Price Points
properties:
  id:
    type: integer
  currency:
    type: string
  price:
    type: integer
  formatted_price:
    type: string
  product_price_point_id:
    type: integer
  role:
    type: string
    enum:
    - baseline
    - trial
    - initial