title: Product
type: object
properties:
  id:
    type: integer
  name:
    type: string
    description: The product name
  handle:
    type: string
    nullable: true
    description: The product API handle
  description:
    type: string
    description: The product description
  accounting_code:
    type: string
    nullable: true
  request_credit_card:
    type: boolean
    description: 'Deprecated value that can be ignored unless you have legacy hosted pages. For Public Signup Page users, please read this attribute from under the signup page.'
  expiration_interval:
    type: integer
    nullable: true
    description: A numerical interval for the length a subscription to this product will run before it expires. See the description of interval for a description of how this value is coupled with an interval unit to calculate the full interval
  expiration_interval_unit:
    type: string
    nullable: true
    description: 'A string representing the trial interval unit for this product, either month or day'
    enum:
      - month
      - day
      - never
      - ''
      - null
  created_at:
    type: string
    description: Timestamp indicating when this product was created
  updated_at:
    type: string
    description: Timestamp indicating when this product was last updated
  price_in_cents:
    type: integer
    description: 'The product price, in integer cents'
  interval:
    type: integer
    description: The numerical interval. i.e. an interval of ‘30’ coupled with an interval_unit of day would mean this product would renew every 30 days
  interval_unit:
    type: string
    description: 'A string representing the interval unit for this product, either month or day'
    enum:
      - month
      - day
  initial_charge_in_cents:
    type: integer
    nullable: true
    description: The up front charge you have specified.
  trial_price_in_cents:
    type: integer
    nullable: true
    description: 'The price of the trial period for a subscription to this product, in integer cents.'
  trial_interval:
    type: integer
    nullable: true
    description: A numerical interval for the length of the trial period of a subscription to this product. See the description of interval for a description of how this value is coupled with an interval unit to calculate the full interval
  trial_interval_unit:
    type: string
    nullable: true
    description: 'A string representing the trial interval unit for this product, either month or day'
    enum:
      - month
      - day
      - null
  archived_at:
    type: string
    nullable: true
    description: Timestamp indicating when this product was archived
  require_credit_card:
    type: boolean
    description: Boolean that controls whether a payment profile is required to be entered for customers wishing to sign up on this product.
  return_params:
    type: string
    nullable: true
  taxable:
    type: boolean
  update_return_url:
    type: string
    nullable: true
    description: The url to which a customer will be returned after a successful account update
  initial_charge_after_trial:
    type: boolean
  version_number:
    type: integer
    description: The version of the product
  update_return_params:
    type: string
    nullable: true
    description: 'The parameters will append to the url after a successful account update. See [help documentation](https://help.chargify.com/products/product-editing.html#return-parameters-after-account-update)'
  product_family:
    $ref: ./Product-Family.yaml
  public_signup_pages:
    type: array
    items:
      type: object
      properties:
        id:
          type: integer
          description: The id of the signup page (public_signup_pages only)
        return_url:
          type: string
          nullable: true
          description: The url to which a customer will be returned after a successful signup (public_signup_pages only)
        return_params:
          type: string
          nullable: true
          description: The params to be appended to the return_url (public_signup_pages only)
        url:
          type: string
          description: The url where the signup page can be viewed (public_signup_pages only)
  product_price_point_name:
    type: string
  request_billing_address:
    type: boolean
    description: A boolean indicating whether to request a billing address on any Self-Service Pages that are used by subscribers of this product.
  require_billing_address:
    type: boolean
    description: 'A boolean indicating whether a billing address is required to add a payment profile, especially at signup.'
  require_shipping_address:
    type: boolean
    description: 'A boolean indicating whether a shipping address is required for the customer, especially at signup.'
  tax_code:
    type: string
    nullable: true
    description: A string representing the tax code related to the product type. This is especially important when using the Avalara service to tax based on locale. This attribute has a max length of 10 characters.
  default_product_price_point_id:
    type: integer
  use_site_exchange_rate:
    type:
      - boolean
      - 'null'
