title: Product Family
type: object
x-tags:
  - Product Families
properties:
  id:
    type: integer
  name:
    type: string
  handle:
    type: string
  accounting_code:
    type: 'null'
  description:
    type: string